<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>AniloxRoll.Monitor.Integration.Tests</RootNamespace>
    <AssemblyName>AniloxRoll.Monitor.Integration.Tests</AssemblyName>
    <LangVersion>7.3</LangVersion>
    <OutputPath>bin\$(Configuration)\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <IsTestProject>true</IsTestProject>
    <ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
    <Platforms>x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.14.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\dotnet\AniloxRoll.Monitor\AniloxRoll.Monitor.csproj" />
    <ProjectReference Include="..\..\sdk\Bridges\IoBridge\IoBridge.Core\IoBridge.Core.csproj" />
    <ProjectReference Include="..\..\sdk\Bridges\StorageBridge\StorageBridge.Core\StorageBridge.Core.csproj" />
  </ItemGroup>

</Project>
